FROM postgres:latest

# Настройки базы данных
ENV POSTGRES_DB=${DB_NAME}
ENV POSTGRES_USER=${DB_USER}
ENV POSTGRES_PASSWORD=${DB_PASSWORD}

# Копируем инициализационные SQL-скрипты в директорию, которая будет автоматически выполнена при запуске контейнера
COPY init.sql /docker-entrypoint-initdb.d/
