version: '3'

services:
  celery:
    build:
      context: .
      dockerfile: ./celery/Dockerfile.celery
    environment:
      - CELERY_BROKER=redis://redis:6379/0

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
