version: '3'

services:
  django:
    build: .
    tty: true
    command: /docker-entrypoint.sh uvicorn app:app --host 0.0.0.0 --port 80
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
      - celery

  db:
    build:
      context: ./postgresql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mydatabasepassword

  redis:
    build:
      context: ./redis

  celery:
    build:
      context: ./celery
    depends_on:
      - django
      - redis
