version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mydatabasepassword

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A your_project_name worker --loglevel=info
    depends_on:
      - web
      - redis
