# Generated by Django 4.2.7 on 2023-11-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('action', models.CharField(max_length=200)),
                ('is_rewarding_habit', models.BooleanField(default=False)),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('reward', models.CharField(max_length=200)),
                ('time_required', models.PositiveIntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.place')),
                ('related_habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
            ],
        ),
    ]
