# Generated by Django 4.2.7 on 2023-11-25 15:59

from django.db import migrations, models
import django.db.models.deletion
import settings_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', validators=[settings_app.validators.validate_related_habit]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_required',
            field=models.PositiveIntegerField(validators=[settings_app.validators.validate_time_required]),
        ),
    ]
