# Generated by Django 4.2.7 on 2023-12-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
